config/routes.rb
Rails.application.routes.draw do
  resources :cars do
    member do
      get :booking, to: "cars#booking"
    end

    collection do
      get :thanks
    end
  end

  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
    has_many_attached :car_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show booking ]

  # GET /cars or /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/booking
  def booking
  end


  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to car_url(@car), notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:make, :model, :km, :latitude, :longitude, :description, :color, :available_from, :available_until, :name, :email, car_image: [])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cars/_car.html.erb
                                <%# All cars page %>

<%# Here is a code from the internet for the distance law %>
<% lat2 = 21.713637%>
<% lon2 = 39.101741%>
<% lat1 = car.latitude%>
<% lon1 = car.longitude%>
<% if ((lat1 == lat2) && (lon1 == lon2))%> 
    <%dist = 0%>
<% else %> 
    <%radlat1 = Math::PI * lat1 / 180%>
    <%radlat2 = Math::PI * lat2 / 180%>
    <%theta = lon1 - lon2%>
    <%radtheta = Math::PI * theta / 180%>
    <%dist = Math.sin(radlat1) * Math.sin(radlat2) + Math.cos(radlat1) * Math.cos(radlat2) * Math.cos(radtheta)%>
    <%if (dist > 1)%> 
      <%dist = 1%>
    <% end %>
    <%dist = Math.acos(dist)%>
    <%dist = dist * 180 / Math::PI%>
    <%dist = dist * 60 * 1.1515%>
    <%dist = dist * 1.609344%>
<%end%>

<%# ----------------------------------------------- %>

<%# Below you can remove the comment to appear if statement to limit cars to 50Km %>
<%# <% if dist<= 50%> 
<div class="pro">
    <%# Here you will only call the first image and make it as the main image %>
    <%= image_tag car.car_image[0] ,class:"img" %>
    <%# Here below we have named the main address, car name and model and all data %>
    <p class="title">
    <%= car.make %>
    <%= car.model %>
    </p>
    <p class="description">
    <strong>Km:</strong>
    <%= car.km %>
    </p>
    <p class="description">
    <strong> Distance: </strong>
    <%# Call the decimal function to shorten the number after the comma %>
    <%= '%.2f' %dist %> 
    </p>
    <p class="bot">
      <%# Go to car detail page %>
      <%= link_to "تفاصيل السيارة", car %>
    </p>

</div>
<%# <%end%> 

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :make, style: "display: block" %>
    <%= form.text_field :make %>
  </div>

  <div>
    <%= form.label :model, style: "display: block" %>
    <%= form.text_field :model %>
  </div>

  <div>
    <%= form.label :km, style: "display: block" %>
    <%= form.text_field :km %>
  </div>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.text_field :longitude %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :color, style: "display: block" %>
    <%= form.text_field :color %>
  </div>

  <div>
    <%= form.label :available_from, style: "display: block" %>
    <%= form.date_field :available_from %>
  </div>

  <div>
    <%= form.label :available_until, style: "display: block" %>
    <%= form.date_field :available_until %>
  </div>

  <div>
    <%= form.label :car_image, style: "display: block" %>
    <%= form.file_field :car_image , multiple: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/booking.html.erb
                                        <%# car booking page %>

<%= form_with id: "myForm" do |form| %>
    <!-- BOOKING FORM -->
        <h2>Reserve your car now </h2>

        <!-- Input list when registering -->
        <label for="name">Name</label>
        <%= form.text_field :name ,name:"name" ,:required => true%>
    
        <label for="email">Email</label>
        <%= form.text_field :email ,name:"email" ,:required => true %>
    
        <label for="checkin-date">Check-in Date</label>
        <%= form.date_field :available_from ,  min: @car.available_from , max: @car.available_until ,id:"checkin-date", name:"checkin" ,:required => true %>
        
        <label for="checkout-date">Check-out Date</label>
        <%= form.date_field :available_until , max: @car.available_until ,id:"checkout-date" , name:"checkout" ,:required => true%>

        <%= button_to "Go!", thanks_cars_path ,:action => "click", id:"bookGo", onclick: "valueSender()" , class:"btn" %>
<% end %>


<!-- Javascript -->
<script>
    window.addEventListener('load', () => { // Here we read all the indexes of cars and know them
        const params = (new URL(document.location)).searchParams;
    })

    // Here we enter the starting and ending number to book each car
    var checkinElem = document.querySelector("#checkin-date");
    var checkoutElem = document.querySelector("#checkout-date");

        checkinElem.onchange = function () {
            // Here it saves the start date that the person chooses and saves it in checkoutElem
            checkoutElem.setAttribute("min", this.value); 

            document.getElementById("bookGo").disabled = false;
        }

        // -------------------------------------

    function valueSender() {
        let Name = document.forms["myForm"]["name"].value;
        let Emil = document.forms["myForm"]["email"].value;
        let In = document.forms["myForm"]["checkin"].value;
        let Out = document.forms["myForm"]["checkout"].value;

        // Error message when leaving any space empty
        if (Name == "") {
            alert("Name must be filled out");
            return false;
        } if (Emil == "") {
            alert("Emil must be filled out");
            return false;
        } if (In == "") {
            alert("checkin must be filled out");
            return false;
        } if (Out == "") {
            alert("checkout must be filled out");
            return false;
        }

        // Here below, a thank you message appears upon completion of the reservation
        var a = 0;
        localStorage.setItem("myValue", a)
        window.location.href = "/cars/thanks";     // Here you go to the thank you page when you're done
        document.getElementById("bookGo").disabled = true;
    }
</script>

app/views/cars/index.html.erb
                                   <%# View all cars page %>

<!-- Home section -->
<p style="color: green"><%= notice %></p>
<section class="home" id="home">
  <div class="swiper-container home-slider">
    <div class="swiper-wrapper wrapper">
      <div class="swiper-slide slide">
          <div class="content">
              <h3>كيفية الاستخدام</h3>
              <p>آدرج سيارتك مجاناً في آول منصة مرخصة لمشاركة السيارات <br> من شخص لشخص في المملكة العربيه السعودية</p>
          </div>
          <div class="image">
              <img src="Images/carw3.jpeg" alt="">
          </div>
      </div>
    </div>
  </div>
</section>

<!-- Cars section -->
<section class=car-list>
<div class="tital"> 
    <h2>قائمة السيارات</h2>
</div>

<%# Call to the car page %>
<div class="pro-cotainer">
  <% @cars.each do |car| %>    
    <%= render car %>
  <% end %>
</div>
</section>

<div class="btn">
<%# Go to the new page to add new cars %>
<%= link_to "أضف سيارة جديدة", new_car_path %>
</div>

app/views/cars/new.html.erb
                                    <%# Add new cars page %>

<h2>أضف معلومات سيارتك</h2>
<%= render "form", car: @car %>
<br>

<div>
  <%= link_to "العودة الى صفحه السيارات", cars_path %>
</div>

app/views/cars/show.html.erb
                        <%# car detail page %>

<%# Here is a code from the internet for the distance law %>
<% lat2 = 21.713637%>
<% lon2 = 39.101741%>
<% lat1 = @car.latitude%>
<% lon1 = @car.longitude%>
<% if ((lat1 == lat2) && (lon1 == lon2))%> 
    <%dist = 0%>
<% else %> 
    <%radlat1 = Math::PI * lat1 / 180%>
    <%radlat2 = Math::PI * lat2 / 180%>
    <%theta = lon1 - lon2%>
    <%radtheta = Math::PI * theta / 180%>
    <%dist = Math.sin(radlat1) * Math.sin(radlat2) + Math.cos(radlat1) * Math.cos(radlat2) * Math.cos(radtheta)%>
    <%if (dist > 1)%> 
      <%dist = 1%>
    <% end %>
    <%dist = Math.acos(dist)%>
    <%dist = dist * 180 / Math::PI%>
    <%dist = dist * 60 * 1.1515%>
    <%dist = dist * 1.609344%>
<%end%>

<%# ------------------------------------------------------- %>

<h2>تفاصيل السيارة</h2>
<p style="color: green"><%= notice %></p>
<h2></h2>
<div class="product">
    <div class="single-pro-img">
          <%=  image_tag  @car.car_image[0], id: "MainImg" %>
        <div class="single-pro-group">
          <% @car.car_image.each do |car_images| %>
            <div class="single-pro-col">
                <%= image_tag car_images ,  onclick: "clickSmall()" ,class: "smallImg"%>
            </div>
          <% end %>
        </div>
    </div>
  <div class="single-pro-details">
    <p class="title">
      <%= @car.make %>
      <%= @car.model %>
    </p>
    <p class="description">
      <strong>Km:</strong>
      <%= @car.km %>
    </p>
    <p class="description">
      <strong> Distance: </strong>
      <%= '%.2f' %dist %>
    </p>

    <p class="description">
      <strong>Description:</strong>
      <%= @car.description %>
    </p>

    <p class="description">
      <strong>Color:</strong>
      <%= @car.color %>
    </p>

    <p class="bot" > 
      <%= link_to "الرجوع الى صفحة السيارات", cars_path, class: "dot" %>
    </p>
      <%= link_to "Book Now", booking_car_path , class: "btn"%>
  </div>
</div>

    
<!-- Javascript -->
<script >
window.addEventListener('load', () => { // Here we read all the indexes of cars and know them
    const params = (new URL(document.location)).searchParams;
})

function clickSmall(){ // At first, you have to double click on the first image to show it
    console.log("asd")
let col = document.getElementsByClassName("smallImg"); // It calls small pictures

    for(var i=0 ; i < col.length; i++){ // Here it calculates the index for all its images and shows them
        col[i].addEventListener('click', function(){

            this.classList.add('smallImg')
            document.getElementById('MainImg').src = this.src
        })
    }
}
</script>

app/views/cars/thanks.html.erb
                        <%# The last page is thanks %>

<div class="box">
<h2>THANK YOU</h2>
<p class="thank">We have received your booking request.</p>
</div>

<script>
    var b = localStorage.getItem("myValue");
    alert("Thank You ..")
    var resetValue = 0;
    localStorage.setItem("myValue" , resetValue)
</script>

app/views/home/_header.html.erb
<div class="nav-container">
            <!-- header list -->
            <!-- nav section in css -->
            <nav>  
                <%= image_tag("logo.png",class: "logo") %>
                <ul>
                    <li><a href="/">الصفحة الرئيسية</a></li>
                    <li><a href="/cars">السيارات</a></li>
                    <li><a href="/#qualites">ماذا نقدم لكم</a></li>
                    <li><a href="/#about">من نحن</a></li>
                    <li><a href="/#contact">تواصل معنا</a></li>
                </ul>
            </nav>
</div>

app/views/home/index.html.erb
       <!-- moving screen -->
            <!-- hero section in css -->
            <div class="hero">
                <div class="content">
                    <h1>آجر <span>سيارتك </span>من بيتك </h1>
                    <h3>
                        <span>Ejaro </span>  هو اول تطبيق مرخص لمشاركة السيارات بين الافراد
                    </h3>
                    <button class="btn"><a href="/cars">السيارات</a></button>
                </div>
            </div>

            <!-- ماذا نقدم لكم All qualites in homepage  -->
            <section id="qualites" class="qualites">
                <h2>ماذا نقدم لكم</h2>
            
                <div class="quality-container">
                    <div class="quality">
                        <div class="header-container">
                            <h3> <i class="fa-solid fa-circle-question"></i>كيفيه الاستخدام</h3>
                        </div> 
                            <p>آدرج سيارتك مجاناً في آول منصة مرخصة لمشاركة السيارات من شخص لشخص في المملكة العربيه السعودية</p>
                    </div>

                    <div class="quality">
                        <div class="header-container">
                            <h3> <i class="fa-solid fa-shield-heart"></i>السلامة والآمان</h3>
                        </div>  
                            <p>نقوم بفحص جميع المستخدمين والمركبات داخل مجتمعنا لراحه بالك</p>
                    </div>

                    <div class="quality">
                        <div class="header-container">
                            <h3> <i class="fa-solid fa-car-burst"></i>التآمين</h3>
                        </div>  
                            <p>تقدم إيجارو آول بوليصة تآمين من شخص لشخص في المملكة لتلبية احتياجاتك</p>
                    </div>
                </div>
            </section>

            <!-- من نحن في هوم بيج -->
            <section id="about" class="about-container">
                <div class="about-us">
                    <div class="about-content">
                        <h2>من نحن؟ </h2>
                        <p>
                            نحن اول مجتمع مرخص لمشاركة المركبات بين الآفراد في المملكة العربيه السعودية ، تقدر تزيد فيها مصدر دخلك بمشاركة سيارتك في التطبيق
                        </p>
                    </div>
                        <%= image_tag("car1.jpeg") %>
                </div>
            </section>

            <!-- تواصل معنا   -->
            <section id="contact" class="cards-contact">
                <h2>تواصل معنا عبر</h2>
                <div class="content-cards">

                    <div class="card">
                        <div class="icon">
                            <i class="fas fa-phone"></i>
                        </div>
                        <div class="info">
                            <h3>الهاتف</h3>
                            <p>920033991</p>
                        </div>
                    </div>

                    <div class="card">
                        <div class="icon">
                            <i class="fas fa-envelope"></i>
                        </div>
                        <div class="info">
                            <h3>البريد الالكتروني</h3>
                            <p>support@ejaro.com</p>
                        </div>
                    </div>

                </div>
            </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir="rtl">
<head>
    <title>Ejaro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <%# <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"> %>
    <link rel="stylesheet" 
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" 
    integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" 
    crossorigin="anonymous" 
    referrerpolicy="no-referrer" />
</head>
<body>

  <%= render 'home/header' %>
  <div class="container">
      <%= yield %> 
  </div>
</body>
</html>